# Generated by Django 3.0 on 2021-01-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='german_language_level',
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
    ]
